# Generated by Django 6.1 on 2026-09-03 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_type', models.CharField(choices=[('resource', 'Resource'), ('skill', 'Skill')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('academic', 'Academic'), ('books', 'Books'), ('technology', 'Technology'), ('electronics', 'Electronics'), ('photography', 'Photography'), ('programming', 'Programming'), ('design', 'Design'), ('sports', 'Sports'), ('other', 'Other')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='listings/')),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair')], max_length=20)),
                ('credit_cost', models.PositiveIntegerField(default=10)),
                ('duration_days', models.PositiveIntegerField(default=7)),
                ('location', models.CharField(default='RCSS Campus', max_length=150)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
